export const products = [{
  'label': 'One',
  'productName': 'Chai',
  'ProductId': 1,
  'CategoryID': 1,
  'QuantityPerUnit': '10 boxes x 20 bags',
  'UnitPrice': 18.0000,
  'UnitsInStock': 39,
  'UnitsOnOrder': 0,
  'ReorderLevel': 10,
  'Discontinued': false,
}, {
  'label': 'two',
  'productName': 'Chang',
  'ProductId': 1,
  'CategoryID': 1,
  'QuantityPerUnit': '24 - 12 oz bottles',
  'UnitPrice': 19.0000,
  'UnitsInStock': 17,
  'UnitsOnOrder': 40,
  'ReorderLevel': 25,
  'Discontinued': false,
}, {
  'label': 'three',
  'productName': 'Aniseed Syrup',
  'ProductId': 1,
  'CategoryID': 2,
  'QuantityPerUnit': '12 - 550 ml bottles',
  'UnitPrice': 10.0000,
  'UnitsInStock': 13,
  'UnitsOnOrder': 70,
  'ReorderLevel': 25,
  'Discontinued': false,
}, {
  'label': 'four',
  'productName': 'Chef Anton\'s Cajun Seasoning',
  'ProductId': 2,
  'CategoryID': 2,
  'QuantityPerUnit': '48 - 6 oz jars',
  'UnitPrice': 22.0000,
  'UnitsInStock': 53,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}, {
  'label': 'five',
  'productName': 'Chef Anton\'s Gumbo Mix',
  'ProductId': 2,
  'CategoryID': 2,
  'QuantityPerUnit': '36 boxes',
  'UnitPrice': 21.3500,
  'UnitsInStock': 0,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': true,
}, {
  'label': 'six',
  'productName': 'Grandma\'s Boysenberry Spread',
  'ProductId': 3,
  'CategoryID': 2,
  'QuantityPerUnit': '12 - 8 oz jars',
  'UnitPrice': 25.0000,
  'UnitsInStock': 120,
  'UnitsOnOrder': 0,
  'ReorderLevel': 25,
  'Discontinued': false,
}, {
  'label': 'seven',
  'productName': 'Uncle Bob\'s Organic Dried Pears',
  'ProductId': 3,
  'CategoryID': 7,
  'QuantityPerUnit': '12 - 1 lb pkgs.',
  'UnitPrice': 30.0000,
  'UnitsInStock': 15,
  'UnitsOnOrder': 0,
  'ReorderLevel': 10,
  'Discontinued': false,
}, {
  'label': 'eight',
  'productName': 'Northwoods Cranberry Sauce',
  'ProductId': 3,
  'CategoryID': 2,
  'QuantityPerUnit': '12 - 12 oz jars',
  'UnitPrice': 40.0000,
  'UnitsInStock': 6,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}, {
  'label': 'nine',
  'productName': 'Mishi Kobe Niku',
  'ProductId': 4,
  'CategoryID': 6,
  'QuantityPerUnit': '18 - 500 g pkgs.',
  'UnitPrice': 97.0000,
  'UnitsInStock': 29,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': true,
}, {
  'label': 'ten',
  'productName': 'Ikura',
  'ProductId': 4,
  'CategoryID': 8,
  'QuantityPerUnit': '12 - 200 ml jars',
  'UnitPrice': 31.0000,
  'UnitsInStock': 31,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}, {
  'label': 'eleven',
  'productName': 'Queso Cabrales',
  'ProductId': 5,
  'CategoryID': 4,
  'QuantityPerUnit': '1 kg pkg.',
  'UnitPrice': 21.0000,
  'UnitsInStock': 22,
  'UnitsOnOrder': 30,
  'ReorderLevel': 30,
  'Discontinued': false,
}, {
  'label': 'twelve',
  'productName': 'Queso Manchego La Pastora',
  'ProductId': 5,
  'CategoryID': 4,
  'QuantityPerUnit': '10 - 500 g pkgs.',
  'UnitPrice': 38.0000,
  'UnitsInStock': 86,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}, {
  'label': 'thirteen',
  'productName': 'Konbu',
  'ProductId': 6,
  'CategoryID': 8,
  'QuantityPerUnit': '2 kg box',
  'UnitPrice': 6.0000,
  'UnitsInStock': 24,
  'UnitsOnOrder': 0,
  'ReorderLevel': 5,
  'Discontinued': false,
}, {
  'label': 'fourteen',
  'productName': 'Tofu',
  'ProductId': 6,
  'CategoryID': 7,
  'QuantityPerUnit': '40 - 100 g pkgs.',
  'UnitPrice': 23.2500,
  'UnitsInStock': 35,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}, {
  'label': 'fifteen',
  'productName': 'Genen Shouyu',
  'ProductId': 6,
  'CategoryID': 2,
  'QuantityPerUnit': '24 - 250 ml bottles',
  'UnitPrice': 15.5000,
  'UnitsInStock': 39,
  'UnitsOnOrder': 0,
  'ReorderLevel': 5,
  'Discontinued': false,
}, {
  'label': 'sixteen',
  'productName': 'Pavlova',
  'ProductId': 7,
  'CategoryID': 3,
  'QuantityPerUnit': '32 - 500 g boxes',
  'UnitPrice': 17.4500,
  'UnitsInStock': 29,
  'UnitsOnOrder': 0,
  'ReorderLevel': 10,
  'Discontinued': false,
}, {
  'label': 'seventeen',
  'productName': 'Alice Mutton',
  'ProductId': 7,
  'CategoryID': 6,
  'QuantityPerUnit': '20 - 1 kg tins',
  'UnitPrice': 39.0000,
  'UnitsInStock': 0,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': true,
}, {
  'label': 'eighteen',
  'productName': 'Carnarvon Tigers',
  'ProductId': 7,
  'CategoryID': 8,
  'QuantityPerUnit': '16 kg pkg.',
  'UnitPrice': 62.5000,
  'UnitsInStock': 42,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}, {
  'label': 'nineteen',
  'productName': 'Teatime Chocolate Biscuits',
  'ProductId': 8,
  'CategoryID': 3,
  'QuantityPerUnit': '10 boxes x 12 pieces',
  'UnitPrice': 9.2000,
  'UnitsInStock': 25,
  'UnitsOnOrder': 0,
  'ReorderLevel': 5,
  'Discontinued': false,
}, {
  'label': 'twenty',
  'productName': 'Sir Rodney\'s Marmalade',
  'ProductId': 8,
  'CategoryID': 3,
  'QuantityPerUnit': '30 gift boxes',
  'UnitPrice': 81.0000,
  'UnitsInStock': 40,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}, {
  'label': 'twenty-one',
  'productName': 'Sir Rodney\'s Scones',
  'ProductId': 8,
  'CategoryID': 3,
  'QuantityPerUnit': '24 pkgs. x 4 pieces',
  'UnitPrice': 10.0000,
  'UnitsInStock': 3,
  'UnitsOnOrder': 40,
  'ReorderLevel': 5,
  'Discontinued': false,
}, {
  'label': 'twenty-two',
  'productName': 'Gustaf\'s Knäckebröd',
  'ProductId': 9,
  'CategoryID': 5,
  'QuantityPerUnit': '24 - 500 g pkgs.',
  'UnitPrice': 21.0000,
  'UnitsInStock': 104,
  'UnitsOnOrder': 0,
  'ReorderLevel': 25,
  'Discontinued': false,
}, {
  'label': 'twenty-three',
  'productName': 'Tunnbröd',
  'ProductId': 9,
  'CategoryID': 5,
  'QuantityPerUnit': '12 - 250 g pkgs.',
  'UnitPrice': 9.0000,
  'UnitsInStock': 61,
  'UnitsOnOrder': 0,
  'ReorderLevel': 25,
  'Discontinued': false,
}, {
  'label': 'twenty-four',
  'productName': 'Guaraná Fantástica',
  'ProductId': 10,
  'CategoryID': 1,
  'QuantityPerUnit': '12 - 355 ml cans',
  'UnitPrice': 4.5000,
  'UnitsInStock': 20,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': true,
}, {
  'label': 'twenty-five',
  'productName': 'NuNuCa Nuß-Nougat-Creme',
  'ProductId': 11,
  'CategoryID': 3,
  'QuantityPerUnit': '20 - 450 g glasses',
  'UnitPrice': 14.0000,
  'UnitsInStock': 76,
  'UnitsOnOrder': 0,
  'ReorderLevel': 30,
  'Discontinued': false,
}, {
  'label': 'twenty-six',
  'productName': 'Gumbär Gummibärchen',
  'ProductId': 11,
  'CategoryID': 3,
  'QuantityPerUnit': '100 - 250 g bags',
  'UnitPrice': 31.2300,
  'UnitsInStock': 15,
  'UnitsOnOrder': 0,
  'ReorderLevel': 0,
  'Discontinued': false,
}];
